### ISSUE TITLE
Installation issued

### ISSUE THREAD

**Issue by kylamon1** [martinfuchs/Godot-Onscreen-Keyboard#1]
You should move all the required files and put them into the correct folder in the github for download. This would prevent the user from having to make the folders before getting the plugin working.

EX: In this github move all files to addons/onscreenkeyboard/... Then when the files get downloaded they are already in the correct folder by default.

See https://github.com/rohanrhu/virtual-joystick for example of what I mean.

I had about 10 minutes of issues from trying to install this from the asset library in Godot(3.5).  
--------------------------------------------------------------
Separate issue
Also why is icon.png required to be in the addons folder for this to work?

**Comment by martinfuchs** [comment]
True. I have changed that. I could not test it because changes take a while.

**Comment by moritz-t-w** [comment]
I have changed this back for Godot 4 to have no subfolders because otherwise it wouldn't be possible to use this as a git module. The install instructions tell the user exactly where to put it, so if you read that I don't see any complications.
