### ISSUE TITLE
Permanent changes to offset values after usage

### ISSUE THREAD

**Issue by moritztim** [martinfuchs/Godot-Onscreen-Keyboard#10]
Whenever I run a scene with the keyboard in it and have the keyboard show and hide again, it changes its actual position in the scene seemingly randomly. Likely related to #7
![image](https://github.com/martinfuchs/Godot-Onscreen-Keyboard/assets/90388353/bddf442b-d466-442b-afd8-086903e8f1df)

**Comment by martinfuchs** [comment]
I am not able to reproduce this with the current version. I have updated the positioning a bit. Perhaps that was a fix?
