### ISSUE TITLE
noob here

### ISSUE THREAD

**Issue by mddm1** [martinfuchs/Godot-Onscreen-Keyboard#11]
I want to use this addon inside godot 4.2.1. and so long it works alright. the problem is that I only got to the "installation" part from the readme here as I am too noob to understand anything past that. 

I just want to know how - when I press "enter" on the keyboard the node to be able to emit a signal or a way to know that enter was pressed and the text inside the lineEdit to be transmitted and manipulated. 
 
Could someone please explain how to do this?

**Comment by martinfuchs** [comment]
You can use the regular signal from godot LineEdit or TextEdit Node:
https://docs.godotengine.org/en/stable/classes/class_lineedit.html
```
text_submitted ( String new_text )
Emitted when the user presses @GlobalScope.KEY_ENTER on the LineEdit.
```

**Comment by martinfuchs** [comment]
see above
