### ISSUE TITLE
mini keyboard in fullscreen mode

### ISSUE THREAD

**Issue by cjalden** [martinfuchs/Godot-Onscreen-Keyboard#4]
When I use full screen a mysterious mini keyboard pops up on the lower left. It goes away when a letter is entered.

<img width="1463" alt="image" src="https://github.com/martinfuchs/Godot-Onscreen-Keyboard/assets/601338/24710d43-d729-49c5-a4c9-bbcfb6e3c701">

**Comment by zadiep** [comment]
both of them are valid?

**Comment by martinfuchs** [comment]
i have to close this issue as the current version for godot 4 should fix this
