### ISSUE TITLE
Characters looks small, cant find way to make them bigger

### ISSUE THREAD

**Issue by andresTapari** [martinfuchs/Godot-Onscreen-Keyboard#8]
![imagen](https://github.com/martinfuchs/Godot-Onscreen-Keyboard/assets/79794569/e7ac9ffa-be1d-4846-8e9b-755ac92d6334)

In resolutions like 1080x1920 the characters looks small and cant find a way to make them biggers.

**Comment by martinfuchs** [comment]
To change the font or font-size add a Theme to the Keyboard:
Control -> Theme -> Default Font -> New Font Variation
Control -> Theme -> Default Font Size

**Comment by martinfuchs** [comment]
just added a property for font-size
